### ISSUE TITLE
is it for web-components?

### ISSUE THREAD

**Issue by tusharmath** [wildlyinaccurate/plait#7]
The documentation says its for webcomponents but doesn't look like its creating webcomponents per say.

**Comment by wildlyinaccurate** [comment]
Plait can be used to build components (or modules, or units, or whatever you want to call them) using web technologies. It has no relation to the set of standards and APIs which constitute [Web Components](https://developer.mozilla.org/en-US/docs/Web/Web_Components) (custom elements, HTML templates, shadow DOM, etc).

Does that answer your question?

**Comment by tusharmath** [comment]
Thanks for the clarification. I think it would be great if you could remove it from the docs as its "wildlyinaccurate" _(don't mind :) )_ and feels like a bait for SEO.
